name: Publish

on: [push, pull_request]

env:
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SDK_VERSION: 6.0.x
  NET_CORE_VERSION: net6.0

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      if: startsWith(matrix.os, 'windows-')
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Verify MSBuild
      if: startsWith(matrix.os, 'windows-')
      run: msbuild -version

    - name: Verify g++ on Linux
      if: startsWith(matrix.os, 'ubuntu-')
      shell: sh
      run: g++ --version

    - name: Verify g++ on macOS
      if: startsWith(matrix.os, 'macos-')
      shell: sh
      run: g++-9 --version

    - name: Restore NuGet Packages
      if: startsWith(matrix.os, 'windows-')
      shell: pwsh
      run: |
        Set-StrictMode -Version Latest

        nuget restore

    - name: Publish ConfigGenerator on Linux
      if: startsWith(matrix.os, 'ubuntu-')
      shell: sh
      run: |
        g++ -o ConfigGenerator Unix-version/src/source.cpp
        mkdir out
        cp "ConfigGenerator" "out/"

    - name: Publish ConfigGenerator on macOS
      if: startsWith(matrix.os, 'macos-')
      shell: sh
      run: |
        g++-9 -o ConfigGenerator Unix-version/src/source.cpp
        mkdir out
        cp "ConfigGenerator" "out/"

    - name: Publish ConfigGenerator on Windows
      if: startsWith(matrix.os, 'windows-')
      shell: pwsh
      run: |
        Set-StrictMode -Version Latest
        $ErrorActionPreference = 'Stop'
        $ProgressPreference = 'SilentlyContinue'

        msbuild -t:Build -p:Configuration=Release -p:OutDir="out\" -nologo

    - name: Create zip file on Linux
      if: startsWith(matrix.os, 'ubuntu-')
      shell: sh
      run: |
        # By default use fastest compression
        seven_zip_args="-mx=1"
        zip_args="-1"
        # Include extra logic for builds marked for release
        case "$GITHUB_REF" in
            "refs/tags/"*)
                # Tweak compression args for release publishing
                seven_zip_args="-mx=9 -mfb=258 -mpass=15"
                zip_args="-9"
        esac
        case "$(uname -s)" in
            "Darwin")
                # We prefer to use zip on OS X as 7z implementation on that OS doesn't handle file permissions (chmod +x)
                if command -v zip >/dev/null; then
                    (
                        cd "${GITHUB_WORKSPACE}/out"
                        zip -q -r $zip_args "../ConfigGenerator-linux.zip" .
                    )
                elif command -v 7z >/dev/null; then
                    7z a -bd -slp -tzip -mm=Deflate $seven_zip_args "out/ConfigGenerator-linux.zip" "${GITHUB_WORKSPACE}/out/*"
                else
                    echo "ERROR: No supported zip tool!"
                    return 1
                fi
                ;;
            *)
                if command -v 7z >/dev/null; then
                    7z a -bd -slp -tzip -mm=Deflate $seven_zip_args "out/ConfigGenerator-linux.zip" "${GITHUB_WORKSPACE}/out/*"
                elif command -v zip >/dev/null; then
                    (
                        cd "${GITHUB_WORKSPACE}/out"
                        zip -q -r $zip_args "../ConfigGenerator-linux.zip" .
                    )
                else
                    echo "ERROR: No supported zip tool!"
                    return 1
                fi
                ;;
        esac

        ls

    - name: Create zip file on macOS
      if: startsWith(matrix.os, 'macos-')
      shell: sh
      run: |
        # By default use fastest compression
        seven_zip_args="-mx=1"
        zip_args="-1"
        # Include extra logic for builds marked for release
        case "$GITHUB_REF" in
            "refs/tags/"*)
                # Tweak compression args for release publishing
                seven_zip_args="-mx=9 -mfb=258 -mpass=15"
                zip_args="-9"
        esac
        case "$(uname -s)" in
            "Darwin")
                # We prefer to use zip on OS X as 7z implementation on that OS doesn't handle file permissions (chmod +x)
                if command -v zip >/dev/null; then
                    (
                        cd "${GITHUB_WORKSPACE}/out"
                        zip -q -r $zip_args "../ConfigGenerator-osx.zip" .
                    )
                elif command -v 7z >/dev/null; then
                    7z a -bd -slp -tzip -mm=Deflate $seven_zip_args "out/ConfigGenerator-osx.zip" "${GITHUB_WORKSPACE}/out/*"
                else
                    echo "ERROR: No supported zip tool!"
                    return 1
                fi
                ;;
            *)
                if command -v 7z >/dev/null; then
                    7z a -bd -slp -tzip -mm=Deflate $seven_zip_args "out/ConfigGenerator-osx.zip" "${GITHUB_WORKSPACE}/out/*"
                elif command -v zip >/dev/null; then
                    (
                        cd "${GITHUB_WORKSPACE}/out"
                        zip -q -r $zip_args "../ConfigGenerator-osx.zip" .
                    )
                else
                    echo "ERROR: No supported zip tool!"
                    return 1
                fi
                ;;
        esac

        ls
        cd out
        ls

    - name: Create zip file on Windows
      if: startsWith(matrix.os, 'windows-')
      shell: pwsh
      run: |
        # By default use fastest compression
        $compressionArgs = '-mx=1'

        # Include extra logic for builds marked for release
        if ($env:GITHUB_REF -like 'refs/tags/*') {
            # Tweak compression args for release publishing
            $compressionArgs = '-mx=9', '-mfb=258', '-mpass=15'
        }

        7z a -bd -slp -tzip -mm=Deflate $compressionArgs "out\ConfigGenerator-win.zip" "$env:GITHUB_WORKSPACE\out\*"

        if ($LastExitCode -ne 0) {
            throw "Last command failed."
        }

    - name: Upload ConfigGenerator-linux
      if: startsWith(matrix.os, 'ubuntu-')
      continue-on-error: true
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Package-ubuntu
        path: out/ConfigGenerator-linux.zip

    - name: Upload ConfigGenerator-osx
      if: startsWith(matrix.os, 'macos-')
      continue-on-error: true
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Package-macos
        path: out/ConfigGenerator-osx.zip

    - name: Upload ConfigGenerator-win
      if: startsWith(matrix.os, 'windows-')
      continue-on-error: true
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Package-windows
        path: out/ConfigGenerator-win.zip

  release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.0.0

    - name: Download package from ubuntu-latest
      uses: actions/download-artifact@v3.0.0
      with:
        name: Package-ubuntu
        path: upload

    - name: Download package from macos-latest
      uses: actions/download-artifact@v3.0.0
      with:
        name: Package-macos
        path: upload

    - name: Download package from windows-latest
      uses: actions/download-artifact@v3.0.0
      with:
        name: Package-windows
        path: upload

    - name: Generate SHA-512 checksums
      shell: sh
      run: |
        set -eu

        (
            cd "upload"

            sha512sum *.zip > SHA512SUMS
        )

    - name: Upload SHA512SUMS
      continue-on-error: true
      uses: actions/upload-artifact@v3.0.0
      with:
        name: SHA512SUMS
        path: upload/SHA512SUMS

    - name: Create Library GitHub release
      id: github_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: v${{ github.ref }}
        prerelease: true

    - name: Upload Package-ubuntu to GitHub release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.github_release.outputs.upload_url }}
        asset_path: upload/ConfigGenerator-linux.zip
        asset_name: ConfigGenerator-linux.zip
        asset_content_type: application/zip

    - name: Upload Package-macos to GitHub release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.github_release.outputs.upload_url }}
        asset_path: upload/ConfigGenerator-osx.zip
        asset_name: ConfigGenerator-osx.zip
        asset_content_type: application/zip

    - name: Upload Package-windows to GitHub release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.github_release.outputs.upload_url }}
        asset_path: upload/ConfigGenerator-win.zip
        asset_name: ConfigGenerator-win.zip
        asset_content_type: application/zip

    - name: Upload SHA512SUMS to GitHub release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.github_release.outputs.upload_url }}
        asset_path: upload/SHA512SUMS
        asset_name: SHA512SUMS
        asset_content_type: text/plain
